@include('website.layouts.common.web._tpl_start')
@include('website.layouts.common.web._header')
@yield('content')
@include('website.layouts.common.web._footer')
@include('website.layouts.common.web._tpl_end')